POST http://localhost:8080/obfuscate?name=test3&timezone=Europe/Berlin&timeframe-start=2024-08-26&timeframe-end=2024-08-31&sections=[["08:00", "12:00"], ["12:00", "18:00"], ["18:00", "23:00"]]
Authorization: Basic user password  // Expects you use "user" and "password"
Content-Type: application/json

[
  "https://antonius.cloud/remote.php/dav/public-calendars/Qq6FCoK8sqr2xNZz?export"
]